In [1]:
import numpy as np

In [2]:
arr1 = np.array([45,59,65,32])
arr1

array([45, 59, 65, 32])

In [3]:
arr1.shape

(4,)

In [5]:
arr1.ndim

1

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr2 = np.array([[45,23,56,25],[87,98,45,60],[450,20,15,12]])
arr2

array([[ 45,  23,  56,  25],
       [ 87,  98,  45,  60],
       [450,  20,  15,  12]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(3, 4)

In [10]:
arr2.dtype

dtype('int32')

In [11]:
np.linspace(10,25)

array([10.        , 10.30612245, 10.6122449 , 10.91836735, 11.2244898 ,
       11.53061224, 11.83673469, 12.14285714, 12.44897959, 12.75510204,
       13.06122449, 13.36734694, 13.67346939, 13.97959184, 14.28571429,
       14.59183673, 14.89795918, 15.20408163, 15.51020408, 15.81632653,
       16.12244898, 16.42857143, 16.73469388, 17.04081633, 17.34693878,
       17.65306122, 17.95918367, 18.26530612, 18.57142857, 18.87755102,
       19.18367347, 19.48979592, 19.79591837, 20.10204082, 20.40816327,
       20.71428571, 21.02040816, 21.32653061, 21.63265306, 21.93877551,
       22.24489796, 22.55102041, 22.85714286, 23.16326531, 23.46938776,
       23.7755102 , 24.08163265, 24.3877551 , 24.69387755, 25.        ])

In [13]:
np.linspace(10,25,25,dtype = 'int64')

array([10, 10, 11, 11, 12, 13, 13, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20,
       20, 21, 21, 22, 23, 23, 24, 25], dtype=int64)

In [14]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones(15) * 2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [20]:
np.eye(6) 

array([[2., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 2.]])

In [29]:
arr3 = np.arange(1,101)
arr3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
arr3 = np.arange(1,101,3)
arr3

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [3]:
arr4 = np.random.randint(45,80)
arr4

46

In [5]:
np.random.seed(1)
arr4 = np.random.randint(45,80,100)
arr4

array([57, 53, 54, 56, 50, 60, 45, 61, 46, 57, 52, 51, 70, 65, 63, 65, 56,
       73, 74, 59, 49, 68, 68, 75, 77, 67, 58, 54, 52, 67, 46, 45, 62, 53,
       69, 58, 53, 75, 52, 48, 51, 66, 48, 49, 69, 57, 71, 61, 63, 60, 45,
       49, 70, 79, 68, 52, 71, 70, 67, 54, 48, 68, 72, 64, 53, 77, 79, 55,
       68, 60, 68, 70, 52, 73, 55, 77, 69, 68, 46, 58, 48, 45, 58, 51, 66,
       51, 47, 57, 72, 66, 56, 52, 58, 53, 56, 57, 65, 75, 52, 49])

In [6]:
arr4 = arr4.reshape(10,10) #reshape convert 1D to 2D
arr4

array([[57, 53, 54, 56, 50, 60, 45, 61, 46, 57],
       [52, 51, 70, 65, 63, 65, 56, 73, 74, 59],
       [49, 68, 68, 75, 77, 67, 58, 54, 52, 67],
       [46, 45, 62, 53, 69, 58, 53, 75, 52, 48],
       [51, 66, 48, 49, 69, 57, 71, 61, 63, 60],
       [45, 49, 70, 79, 68, 52, 71, 70, 67, 54],
       [48, 68, 72, 64, 53, 77, 79, 55, 68, 60],
       [68, 70, 52, 73, 55, 77, 69, 68, 46, 58],
       [48, 45, 58, 51, 66, 51, 47, 57, 72, 66],
       [56, 52, 58, 53, 56, 57, 65, 75, 52, 49]])

In [7]:
arr4[4,5]

57

In [8]:
arr4[3:8,3:8]

array([[53, 69, 58, 53, 75],
       [49, 69, 57, 71, 61],
       [79, 68, 52, 71, 70],
       [64, 53, 77, 79, 55],
       [73, 55, 77, 69, 68]])

In [10]:
arr4[3:8,3:8] = 50
arr4

array([[57, 53, 54, 56, 50, 60, 45, 61, 46, 57],
       [52, 51, 70, 65, 63, 65, 56, 73, 74, 59],
       [49, 68, 68, 75, 77, 67, 58, 54, 52, 67],
       [46, 45, 62, 50, 50, 50, 50, 50, 52, 48],
       [51, 66, 48, 50, 50, 50, 50, 50, 63, 60],
       [45, 49, 70, 50, 50, 50, 50, 50, 67, 54],
       [48, 68, 72, 50, 50, 50, 50, 50, 68, 60],
       [68, 70, 52, 50, 50, 50, 50, 50, 46, 58],
       [48, 45, 58, 51, 66, 51, 47, 57, 72, 66],
       [56, 52, 58, 53, 56, 57, 65, 75, 52, 49]])

In [11]:
arr4.flatten() #flatten is to return 2D to 1D

array([57, 53, 54, 56, 50, 60, 45, 61, 46, 57, 52, 51, 70, 65, 63, 65, 56,
       73, 74, 59, 49, 68, 68, 75, 77, 67, 58, 54, 52, 67, 46, 45, 62, 50,
       50, 50, 50, 50, 52, 48, 51, 66, 48, 50, 50, 50, 50, 50, 63, 60, 45,
       49, 70, 50, 50, 50, 50, 50, 67, 54, 48, 68, 72, 50, 50, 50, 50, 50,
       68, 60, 68, 70, 52, 50, 50, 50, 50, 50, 46, 58, 48, 45, 58, 51, 66,
       51, 47, 57, 72, 66, 56, 52, 58, 53, 56, 57, 65, 75, 52, 49])

In [12]:
arr4[arr4>50] #shows all the numbers that are greater than 50

array([57, 53, 54, 56, 60, 61, 57, 52, 51, 70, 65, 63, 65, 56, 73, 74, 59,
       68, 68, 75, 77, 67, 58, 54, 52, 67, 62, 52, 51, 66, 63, 60, 70, 67,
       54, 68, 72, 68, 60, 68, 70, 52, 58, 58, 51, 66, 51, 57, 72, 66, 56,
       52, 58, 53, 56, 57, 65, 75, 52])

In [13]:
arr4[arr4 == 50]

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50, 50, 50, 50, 50, 50, 50])

In [14]:
np.sum(arr4)

5622

In [15]:
np.mean(arr4)

56.22

In [16]:
np.median(arr4)

52.0

In [17]:
np.std(arr4)

8.463545356409451

In [19]:
np.var(arr4)

71.63159999999999

In [20]:
np.sqrt(arr4)

array([[7.54983444, 7.28010989, 7.34846923, 7.48331477, 7.07106781,
        7.74596669, 6.70820393, 7.81024968, 6.78232998, 7.54983444],
       [7.21110255, 7.14142843, 8.36660027, 8.06225775, 7.93725393,
        8.06225775, 7.48331477, 8.54400375, 8.60232527, 7.68114575],
       [7.        , 8.24621125, 8.24621125, 8.66025404, 8.77496439,
        8.18535277, 7.61577311, 7.34846923, 7.21110255, 8.18535277],
       [6.78232998, 6.70820393, 7.87400787, 7.07106781, 7.07106781,
        7.07106781, 7.07106781, 7.07106781, 7.21110255, 6.92820323],
       [7.14142843, 8.1240384 , 6.92820323, 7.07106781, 7.07106781,
        7.07106781, 7.07106781, 7.07106781, 7.93725393, 7.74596669],
       [6.70820393, 7.        , 8.36660027, 7.07106781, 7.07106781,
        7.07106781, 7.07106781, 7.07106781, 8.18535277, 7.34846923],
       [6.92820323, 8.24621125, 8.48528137, 7.07106781, 7.07106781,
        7.07106781, 7.07106781, 7.07106781, 8.24621125, 7.74596669],
       [8.24621125, 8.36660027, 7.2111025

In [21]:
np.max(arr4)

77

In [22]:
np.min(arr4)

45

In [23]:
np.argmax(arr4) #it returns the location of the maximum value

24

In [24]:
np.argmin(arr4)

6

In [25]:
np.percentile(arr4,20)

50.0

In [26]:
np.percentile(arr4,75)

63.0

In [27]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [ ]:
#generate a random array between 50 and 105 consisting of 400 values, reshape this array to equal rows and columns
#retrieve the values from the 5t to 10th and 7th to 15th column
##write a condition to retrieve values >=70
#return the output of the following operations
#sum of the array, max value, min values, 25,,80,85,90,95 percentile

In [28]:
arr5 = np.arange(50,106)
arr5

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105])

In [30]:
np.linspace(50,106,400,dtype = 'int64')

array([ 50,  50,  50,  50,  50,  50,  50,  50,  51,  51,  51,  51,  51,
        51,  51,  52,  52,  52,  52,  52,  52,  52,  53,  53,  53,  53,
        53,  53,  53,  54,  54,  54,  54,  54,  54,  54,  55,  55,  55,
        55,  55,  55,  55,  56,  56,  56,  56,  56,  56,  56,  57,  57,
        57,  57,  57,  57,  57,  58,  58,  58,  58,  58,  58,  58,  58,
        59,  59,  59,  59,  59,  59,  59,  60,  60,  60,  60,  60,  60,
        60,  61,  61,  61,  61,  61,  61,  61,  62,  62,  62,  62,  62,
        62,  62,  63,  63,  63,  63,  63,  63,  63,  64,  64,  64,  64,
        64,  64,  64,  65,  65,  65,  65,  65,  65,  65,  66,  66,  66,
        66,  66,  66,  66,  66,  67,  67,  67,  67,  67,  67,  67,  68,
        68,  68,  68,  68,  68,  68,  69,  69,  69,  69,  69,  69,  69,
        70,  70,  70,  70,  70,  70,  70,  71,  71,  71,  71,  71,  71,
        71,  72,  72,  72,  72,  72,  72,  72,  73,  73,  73,  73,  73,
        73,  73,  74,  74,  74,  74,  74,  74,  74,  74,  75,  7

In [32]:
arr4 = np.random.randint(50,105,400)
arr4

array([ 68,  82,  63,  60,  73,  67,  57,  74,  60,  78,  70,  82,  62,
        51,  80,  91,  74,  68, 101,  83,  52,  94,  78,  89,  84,  60,
       104,  82,  91,  68,  72,  56,  52,  57,  89,  98, 104,  65,  55,
        67,  92,  70, 104,  98,  72,  87,  63,  99, 100,  83, 103,  70,
        60,  82,  75,  71,  89,  82,  69,  75,  99,  64,  63,  70, 102,
        93,  56,  63,  65,  74,  59,  52,  57, 103,  55,  86,  87,  71,
        90,  63,  77,  99,  99,  97,  63,  90,  64,  95,  73,  66,  78,
        92,  95,  53, 102,  52,  64,  96,  50,  79,  61,  85, 103,  79,
        83,  52,  70,  69,  98, 104,  82,  78,  68,  81,  78,  80,  60,
        58,  95,  85,  82,  58,  70,  63, 100,  65,  91,  50,  94,  69,
        74,  99,  92,  70,  94,  65,  80,  77,  64, 101,  69,  76,  93,
        72,  57,  85, 103,  97,  96, 101,  84,  86,  86,  82,  69,  53,
        74,  69,  87,  80,  88,  97,  89,  55,  65,  99,  73,  82,  92,
        60,  52,  74,  84,  80,  67,  54,  50, 102,  64,  67,  8

In [46]:
arr4 = arr4.reshape(20,20) #reshape convert 1D to 2D
arr4

array([[ 68,  82,  63,  60,  73,  67,  57,  74,  60,  78,  70,  82,  62,
         51,  80,  91,  74,  68, 101,  83],
       [ 52,  94,  78,  89,  84,  60, 104,  82,  91,  68,  72,  56,  52,
         57,  89,  98, 104,  65,  55,  67],
       [ 92,  70, 104,  98,  72,  87,  63,  99, 100,  83, 103,  70,  60,
         82,  75,  71,  89,  82,  69,  75],
       [ 99,  64,  63,  70, 102,  93,  56,  63,  65,  74,  59,  52,  57,
        103,  55,  86,  87,  71,  90,  63],
       [ 77,  99,  99,  97,  63,  90,  64,  95,  73,  66,  78,  92,  95,
         53, 102,  52,  64,  96,  50,  79],
       [ 61,  85, 103,  79,  83,  52,  70,  69,  98, 104,  82,  78,  68,
         81,  78,  80,  60,  58,  95,  85],
       [ 82,  58,  70,  63, 100,  65,  91,  50,  94,  69,  74,  99,  92,
         70,  94,  65,  80,  77,  64, 101],
       [ 69,  76,  93,  72,  57,  85, 103,  97,  96, 101,  84,  86,  86,
         82,  69,  53,  74,  69,  87,  80],
       [ 88,  97,  89,  55,  65,  99,  73,  82,  92,  60,  52,  

In [36]:
arr4[5:10,7:15]

array([[82, 69, 75],
       [63, 65, 74],
       [71, 90, 63],
       [95, 73, 66],
       [96, 50, 79]])

In [37]:
arr4[arr4>=70] #shows all the numbers that are greater than 50

array([ 82,  73,  74,  78,  70,  82,  80,  91,  74, 101,  83,  94,  78,
        89,  84, 104,  82,  91,  72,  89,  98, 104,  92,  70, 104,  98,
        72,  87,  99, 100,  83, 103,  70,  82,  75,  71,  89,  82,  75,
        99,  70, 102,  93,  74, 103,  86,  87,  71,  90,  77,  99,  99,
        97,  90,  95,  73,  78,  92,  95, 102,  96,  79,  85, 103,  79,
        83,  70,  98, 104,  82,  78,  81,  78,  80,  95,  85,  82,  70,
       100,  91,  94,  74,  99,  92,  70,  94,  80,  77, 101,  76,  93,
        72,  85, 103,  97,  96, 101,  84,  86,  86,  82,  74,  87,  80,
        88,  97,  89,  99,  73,  82,  92,  74,  84,  80, 102,  89,  85,
        78,  72,  88,  91,  75,  88,  98,  98, 100,  94,  91, 104,  72,
        98,  78, 101,  97,  73,  71,  96,  74,  96, 104,  75, 103,  70,
        71, 100,  96,  79,  94,  87,  72,  77, 104,  76,  73,  89,  93,
       100,  88,  77,  98,  84,  83,  93,  76, 102,  75,  77,  93,  80,
        82,  76,  70,  80,  89,  72,  84, 102,  89,  88,  97,  9

In [38]:
np.sum(arr4)

31172

In [39]:
np.max(arr4)

104

In [40]:
np.min(arr4)

50

In [41]:
np.percentile(arr4,25)

65.0

In [42]:
np.percentile(arr4,80)

93.0

In [43]:
np.percentile(arr4,85)

96.0

In [44]:
np.percentile(arr4,90)

99.0

In [45]:
np.percentile(arr4,95)

102.0

# PANDAS

In [47]:
import pandas as pd
print (dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat

In [49]:
fruits = ['Apple','Cherry','Lemon','Grape']
values = [400,50,205,156]
s1 = pd.Series(data = values,index = fruits)
s1

Apple     400
Cherry     50
Lemon     205
Grape     156
dtype: int64

In [50]:
s1['Cherry']

50

In [51]:
s2 = pd.Series(data = values)
s2

0    400
1     50
2    205
3    156
dtype: int64